---
title: "**МАТЕМАТИЧЕСКОЕ МОДЕЛИРОВАНИЕ В ЭКОЛОГИИ**"
author: "BARYSHKINA TATYANA"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Создание моделей линейной регрессии дневных потоков углекислого газа за летний период 2013 года по данным измерений методом турбулентной пульсации

Предвидеть ответные реакции системы на действие конкретных факторов можно лишь через сложный анализ существующих в ней количественных взаимоотношений и закономерностей. В экологии, поэтому широкое распространение получил метод математического моделирования как средство изучения и прогнозирования природных процессов.

##*Работа с  данными*

Необходимо создать модель линейной регрессии дневных потоков углекислого газа за летний период 2013 года по данным измерений методом турбулентной пульсации.

###*Обработка первоначальных данных*

Для создания модели линейной регрессии дневных потоков углекислого газа были взяты данные за летний период 2013 года по данным измерений методом турбулентной пульсации. Этим данным присвоили имя «br» для более удобной работы.

__tbl = read.csv(eddypro.csv")__

В ходе запуска файла «br» выяснилось, что переменная представляет собой огромный массив данных, который необходимо преобразовать для дальнейшей работы. полученные данные являются машинно-сгенерированными и для обозначения отсутствия данных генератором использовалось значение -9999. Это значение несет в себе информацию аналогичную значению NA в R, а значит должны найти и заменить все такие значения. 

__br=read.csv("eddypro.csv", skip = 1, na =c("","NA","-9999","-9999.0"), comment=c("["))__
__names(br)__

В исследуемому массиве данных присутствовали также текстовые данные, которые мы удалили,  иначе они помешали бы проведению корреляции.

__br<-br[,c(-1,-3,-9,-12,-15,-18,-21,-30,-35,-70,-88:-99)]__
__names(br)__

Подобные преобразования помогли привести массив данных в адекватный вид

Данная работа посвящена созданию модели линейной регрессии именно для дневных потоков углекислого газа за летний период. Поэтому следующим действием было изъятие из общего массива данных нужного периода с показателями. Рассматриваемым периодом оказался период с 05.06.2013 по 05.09.2013 гг.

__br = subset(br, as.Date(date) >= as.Date("2013-06-05") & as.Date(date) <= as.Date("2013-09-05") & daytime == T)__

Переменная roll содержит только NA, а потому будет только мешать при анализе, следовательно, необходимо избавимся от нее с помощью функции select.

__br = select(br, -(roll))__

Все имена таблицы должны быть некоторым вектором строк от функции str_replace_all, которая в свою очередь берет все имена из таблицы tbl, заменяет в них все ! на “emph” и возвращает их в виде вектора. Все довольно наглядно, но проблема в том, что необходимо делать такое последовательно много раз (т.к. нужно избавиться не только от !), что приведет к совершенно не читаемому результату. Поэтому необходимо воспользоваться оператором пайппинга.

names(br) = names(br) %>% 

  str_replace_all("[!]","_emph_") %>% 
  
  str_replace_all("[?]","_quest_") %>% 
  
  str_replace_all("[*]","_star_") %>% 
  
  str_replace_all("[+]","_plus_") %>% 
  
  str_replace_all("[-]","_minus_") %>% 
  
  str_replace_all("[@]","_at_") %>%
  
  str_replace_all("[$]","_dollar_") %>% 
  
  str_replace_all("[#]","_hash_") %>% 
  
  str_replace_all("[/]","_div_") %>% 
  
  str_replace_all("[%]","_perc_") %>% 
  
  str_replace_all("[&]","_amp_") %>%
  
  str_replace_all("[\\^]","_power_") %>% 
  
  str_replace_all("[()]","_") 
  
glimpse(br)

##*Корреляционный анализ*

Функция cor работает только с численными данными, поэтому, чтобы перейти к корелляционному анализу нужно выбрать все переменные типа numeric. Для этого воспользуемся двумя функциями - is.numeric(), которая выдает TRUE в случае если вектор является численныи и sapply(), которая берет каждую колонку таблицы, передает ее в функию в виде вектора (в нашем случае этой функцией будет is.numeric) и выдает результат в виде вектора длинной равной количеству колонок в таблице.

sapply(br,is.numeric)

br_numeric = br[,sapply(br,is.numeric)]

cor_td = cor(br_numeric) 

cor_td

cor_td = cor(drop_na(br_numeric)) %>% as.data.frame %>% select(co2_flux) 

vars = row.names(cor_td)[cor_td$co2_flux^2 > .1] %>% na.exclude 

vars

##*Получение формулы и создание модели*

После проведения корреляции получилась формула зависимости углекислого газа от переменных. Полученные данные корреляции нужно собрать в модель и провести дальнейший анализ, исключая из модели не в полной мере влияющие на углекислый газ переменные.
Собрать все переменные из вектора с именами переменных в одну формулу можно следующим образом:

formula = as.formula(paste("co2_flux~", paste(vars,collapse = "+"), sep=""))
formula

Также создали  непересекающиеся подвыборки с помощью  базового набором функций:

row_numbers = 1:length(br$date) 

teach = sample(row_numbers, floor(length(br$date)*.7)) 

test = row_numbers[-teach] 

teaching_br_unq = br[teach,]

testing_br_unq = br[test,]

На данном этапе создаем и проводим анализ модели множественной регрессии c взаимодействием.

__mod1 = lm(co2_flux ~ (DOY + Tau +rand_err_Tau + H + LE + rand_err_LE + h2o_flux + rand_err_h2o_flux + co2_molar_density + co2_mixing_ratio + RH + VPD + max_speed + TKE  + un_H + un_LE + un_h2o_flux + u_var + v_var + co2_signal_strength_7200 + flowrate)^2,data=br)__

coef(mod1) 

resid(mod1) 

confint(mod1)

summary(mod1)

R2 равен 1, поэтому убираем лишние переменные и взаимодействия с высокими Р-значениями

__anova(model1)__

После этого создаем mod2 и рабаем с ней также как и с mod1.

__mod2 = lm(co2_flux ~ (DOY + Tau +rand_err_Tau + H + LE + rand_err_LE + h2o_flux + rand_err_h2o_flux + co2_molar_density + co2_mixing_ratio + RH + VPD + max_speed + un_LE + un_h2o_flux + co2_signal_strength_7200 + flowrate)^2,data=br)__

coef(mod2) 

resid(mod2) 

confint(mod2)

summary(mod2)

__anova(mod2)__

Проанализировав mod2 можно сказать, что, факторов, влияющих на углекислый газ становится меньше. Эта модель точнее первой, однако она нам не подходит. Исключим из этой модели несколько переменных, и создадим mod3.

__mod3 = lm(co2_flux ~ (DOY + Tau +rand_err_Tau + H + LE + rand_err_LE + h2o_flux + rand_err_h2o_flux + co2_molar_density + co2_mixing_ratio + RH + VPD + max_speed + un_LE + un_h2o_flux + co2_signal_strength_7200 + flowrate)^2-DOY:VPD - DOY:un_LE - DOY:flowrate - Tau:LE - Tau:rand_err_LE - Tau:h2o_flux - Tau:rand_err_h2o_flux - Tau:co2_mixing_ratio - Tau:VPD - Tau:max_speed - Tau:un_LE - Tau:un_h2o_flux - Tau:co2_signal_strength_7200 - rand_err_Tau:rand_err_h2o_flux - rand_err_Tau:co2_molar_density - rand_err_Tau:co2_mixing_ratio - rand_err_Tau:VPD - rand_err_Tau:un_LE - rand_err_Tau:un_h2o_flux - rand_err_Tau:co2_signal_strength_7200 - H:rand_err_LE - H:h2o_flux - H:rand_err_h2o_flux - H:VPD - H:max_speed - H:un_h2o_flux - H:flowrate - LE:h2o_flux - LE:co2_molar_density - LE:co2_mixing_ratio - LE:max_speed - LE:un_LE - LE:un_h2o_flux - LE:co2_signal_strength_7200 - LE:flowrate - rand_err_LE:rand_err_h2o_flux - rand_err_LE:co2_molar_density - rand_err_LE:RH - rand_err_LE:VPD - rand_err_LE:max_speed - rand_err_LE:un_LE - rand_err_LE:un_h2o_flux - h2o_flux:co2_molar_density - h2o_flux:RH - h2o_flux:VPD - h2o_flux:max_speed -h2o_flux:un_h2o_flux - h2o_flux:co2_signal_strength_7200 - h2o_flux:flowrate -rand_err_h2o_flux:RH - rand_err_h2o_flux:VPD - rand_err_h2o_flux:flowrate - co2_molar_density:max_speed - co2_molar_density:co2_signal_strength_7200 - co2_mixing_ratio:co2_signal_strength_7200 - RH:VPD - RH:un_h2o_flux -RH:flowrate - VPD:un_h2o_flux - VPD:co2_signal_strength_7200 - un_h2o_flux:co2_signal_strength_7200 - co2_signal_strength_7200:flowrate -un_LE:co2_signal_strength_7200 - max_speed:un_h2o_flux -max_speed:un_LE - VPD:flowrate - RH:co2_signal_strength_7200 - un_LE:un_h2o_flux - VPD:un_LE - co2_mixing_ratio:flowrate -co2_molar_density:un_LE - rand_err_LE:co2_mixing_ratio -h2o_flux:un_LE - rand_err_Tau:flowrate - DOY:un_h2o_flux -Tau:flowrate - co2_mixing_ratio:max_speed - co2_mixing_ratio:VPD - co2_mixing_ratio:RH ,data=br)__

coef(mod3) 

resid(mod3) 

confint(mod3)

summary(mod3)

__anova(mob3)__

anova(mod3)
DOY                                        ***

Tau                                        ***

rand_err_Tau                               ***

H                                          ***

LE                                         ***

rand_err_LE                                ***

h2o_flux                                   ***

rand_err_h2o_flux                          ** 

co2_molar_density                          ***

co2_mixing_ratio                           ***

RH                                         ***

VPD                                        ***

max_speed                                  ** 

un_LE                                      ***

un_h2o_flux                                ***

co2_signal_strength_7200                   ***

flowrate                                   ***

DOY:Tau                                    ***

DOY:rand_err_Tau                           ***

DOY:H                                      ***

DOY:LE                                     ***

DOY:rand_err_LE                            ***

DOY:h2o_flux                               ***

DOY:rand_err_h2o_flux                      ** 

DOY:co2_molar_density                      ***

DOY:co2_mixing_ratio                       ***

DOY:RH                                     ***

DOY:max_speed                              ***

DOY:co2_signal_strength_7200               ***

Tau:H                                      ***

Tau:co2_molar_density                      ** 

Tau:RH                                     ***

rand_err_Tau:H                             ***

rand_err_Tau:LE                            ** 

rand_err_Tau:rand_err_LE                   ***

rand_err_Tau:h2o_flux                      ***

rand_err_Tau:RH                            ***

rand_err_Tau:max_speed                     ***

H:LE                                       ***

H:co2_molar_density                        ***

H:co2_mixing_ratio                         ***

H:RH                                       ***

H:un_LE                                    ***

H:co2_signal_strength_7200                 ***

LE:rand_err_LE                             ***

LE:rand_err_h2o_flux                       ***

LE:RH                                      ***

rand_err_LE:flowrate                       ***

h2o_flux:rand_err_h2o_flux                 ***

h2o_flux:co2_mixing_ratio                  ***

rand_err_h2o_flux:co2_mixing_ratio         ***

rand_err_h2o_flux:co2_signal_strength_7200 ***

co2_molar_density:co2_mixing_ratio         ** 

co2_molar_density:RH                       ***

co2_molar_density:VPD                      ***


co2_mixing_ratio:un_LE                     ***

co2_mixing_ratio:un_h2o_flux               ** 

RH:max_speed                               ** 

RH:un_LE                                   ** 

VPD:max_speed                              ***

max_speed:co2_signal_strength_7200         ***

max_speed:flowrate                         ***

un_LE:flowrate                             ***

un_h2o_flux:flowrate                          

Проанализировав полностью mod3, мы видим, что больше всего на дневной поток углекислого газа в летний период оказывают оставшиеся параметры, которые мы получили после anova(mod3).

##Спасибо за внимание!



